// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/skeleton-redesign/CleanFocus.tsx": () => import("../components/mockups/skeleton-redesign/CleanFocus.tsx"),
  "./components/mockups/skeleton-redesign/CoachView.tsx": () => import("../components/mockups/skeleton-redesign/CoachView.tsx"),
  "./components/mockups/skeleton-redesign/Combined.tsx": () => import("../components/mockups/skeleton-redesign/Combined.tsx"),
  "./components/mockups/skeleton-redesign/FrameGallery.tsx": () => import("../components/mockups/skeleton-redesign/FrameGallery.tsx"),
  "./components/mockups/skeleton-redesign/ReportCard.tsx": () => import("../components/mockups/skeleton-redesign/ReportCard.tsx"),
  "./components/mockups/skeleton-redesign/StoryMode.tsx": () => import("../components/mockups/skeleton-redesign/StoryMode.tsx")
};
